### ISSUE TITLE
张量大小不匹配

### ISSUE THREAD

**Issue by SoluteToNight** [jiexiaou/HomoFormer#4]
test_M中合并图像时报错
`The size of tensor a (219) must match the size of tensor b (384) at non-singleton dimension 3
  File "/home/nemo/Downloads/HomoFormer/utils/image_utils.py", line 200, in mergeimage
    merge_img[:, :, hs:hs + crop_size, ws:ws + crop_size] += scoremap * simg
  File "/home/nemo/Downloads/HomoFormer/test_M.py", line 109, in <module>
    mergeimage(split_data, starts, crop_size=tile, resolution=(B, C, H, W)))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The size of tensor a (219) must match the size of tensor b (384) at non-singleton dimension 3`

**Comment by jiexiaou** [comment]
你好，能提供一下测试的命令吗

**Comment by SoluteToNight** [comment]
`python test_M.py --input_dir /home/nemo/Downloads/SRD --weights /home/nemo/Downloads/models/SRD.pth --arch HomoFormer --cal_metrics  --result_ /home/nemo/Downloads/output --save_images --gpus 0 --repeat 1 --base_repeat 1`SRD数据集

**Comment by jiexiaou** [comment]
我测试了一下是可以正常运行的
<img width="772" alt="截屏2024-10-24 09 31 53" src="https://github.com/user-attachments/assets/3b22fd47-0188-4753-a5d0-d59a0cf65411">
请确保更新到repo的最新版本，运行命令是：
python test_M.py --input_dir /home/nemo/Downloads/SRD --weights /home/nemo/Downloads/models/SRD.pth --arch HomoFormer --cal_metrics  --result_ /home/nemo/Downloads/output --save_images --gpus 0 --repeat 1 --base_repeat 1 --tile 384 --tile_overlap 30
