### ISSUE TITLE
About the evaluation

### ISSUE THREAD

**Issue by RICKand-MORTY** [jiexiaou/HomoFormer#6]
1. I also encountered this issue when I tried to calculate PSNR and SSIM by using test_M.py, could you please provide the parameter? The issue is :https://github.com/GuoLanqing/ShadowFormer/issues/38#issue-2605870489
2. Are all the results of your paper obtained by evaluating images with a size of 256x256? Or some still in the original image size? 

Thank you very much!

**Comment by jiexiaou** [comment]
1. The data_range in test_M.py is [0, 1].  You can also output this max/min value in other evaluation code.
2. The results are obtained using test_M.py, which evaluates images with resolution 256x256.

**Comment by RICKand-MORTY** [comment]
Thanks for your reply!

**Comment by shanks200199** [comment]
> 1. The data_range in test_M.py is [0, 1].  You can also output this max/min value in other evaluation code.
> 2. The results are obtained using test_M.py, which evaluates images with resolution 256x256.

Hello, how do I evaluate, resize256x256， The result I output using the author's code is very poor, but it is normal at the original resolution. Could you please give me an answer

**Comment by jck666666** [comment]
> > 1. The data_range in test_M.py is [0, 1].  You can also output this max/min value in other evaluation code.
> > 2. The results are obtained using test_M.py, which evaluates images with resolution 256x256.
> 
> Hello, how do I evaluate, resize256x256， The result I output using the author's code is very poor, but it is normal at the original resolution. Could you please give me an answer

Hello, I have the same question. 
Do you solve it?
